# ---------------------------------------------------------------------
# skillet preamble information used by panhandler
# unique snippet name
name: TAPModePoC
# label used for menu selection
label: TAP Mode PoC
description: Generic config for TAP mode to start a PoC
type: panos
extends:
labels:
  collection:
    - MobileSkillet
# end of preamble section
# ---------------------------------------------------------------------
# variables section
# whenever you edit this skillet and add variables below keep it short and crisp
# the idea is not to replace one GUI with another but to have one easy button
variables:
#
 - name: UEIPPool
   description: IP Pool for own subscribers UE (private IPs that often overlap for roaming subs)
   default: 100.64.0.0/16
   type_hint: text

 - name: SFN35ServerIP
   description: IP address of SFN3.5 Server (do not put a netmask here)
   default: 10.0.0.1
   type_hint: text

 - name: TAPNIC
   description: Interface for TAP zone (skillet hangs if nic not free for conf into TAPZONE)
   default: ethernet1/1
   type_hint: text

#
# ---------------------------------------------------------------------
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
#
#---------------------------------------------------------------------
# Static Snippets (no variables at all)
#---------------------------------------------------------------------
 - name: DiskLogQuotaAndEnableSCTPGTP
   xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig
   file: DiskLogQuotaAndEnableSCTPGTP.static.xml

 - name: ZoneProtect_IPOnly
   xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile
   file: ZoneProtectIPOnly.static.xml

 - name: GTPProfile
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/gtp
   file: GTPProfileLogTunnel.static.xml

 - name: SCTPProfile
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/sctp
   file: SCTPProfileCommonS6SS7.static.xml

 - name: VulnProfile_FloodAndBrute
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/vulnerability
   file: VulnProfile_FloodAndBrute.static.xml

 - name: SFNForwardingProfile
   xpath: /config/shared/log-settings/profiles
   file: SFNForwardingProfile.static.xml
#---------------------------------------------------------------------
# Dynamic Snippets (i.e. those here below use variables)
#---------------------------------------------------------------------

 - name: Objects
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
   file: AddrObject.xml

 - name: SFNServerProfile
   xpath: /config/shared/log-settings/syslog
   file: SFNServerProfile.xml

 - name: Interface
   xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface/ethernet
   file: TAPNIC.xml

 - name: Zone
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
   file: Zone.xml

 - name: Rules
   xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security/rules
   file: RulesPOCTAPGeneric.xml

#
